command:
  - npm
  - run
  - start
env:
  - name: DATABRICKS_HOST
    value: "https://adb-5672234203219303.3.azuredatabricks.net"
  - name: VS_INDEX_NAME
    value: "tws_ro_region5.rcd.pa_appeals_chunks_vs_index"
  - name: VS_ENDPOINT_NAME
    value: "pa-appeals-search-endpoint"
  - name: PROCESSOR_NOTEBOOK_PATH
    value: "/Users/0492734585@fema.dhs.gov/pa-appeals-and-policy-search/PA Appeals PDF Incremental Processor"
  - name: APPEALS_VOLUME_PATH
    value: "/Volumes/tws_ro_region5/rcd/pa_second_appeals"
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom:
      resourceRef:
        name: sql-warehouse
  - name: DOCUMENTS_TABLE
    value: ""
  - name: PAGES_TABLE
    value: ""
